version: "3.1"

services:
  testproject-agent:
    image: testproject/agent:latest
    container_name: testproject-agent
    depends_on:
      - chrome
      - firefox
    volumes:
      - /usr/bin:/var/testproject/agent
    environment:
      TP_API_KEY: "EfUCtCDNcaXrUdVXoRZ9ZlBA16QB7Af0TRWWAutIY8k1"
      TP_SDK_PORT: "8686"
      CHROME: "chrome:4444"
      FIREFOX: "firefox:4444"
  chrome:
    image: selenium/standalone-chrome:3.141.59
    shm_size: '1gb'
    ports:
      - "4444:4444"

  firefox:
    image: selenium/standalone-firefox:3.141.59
    shm_size: '1gb'
